// ================================================================
// JBRETAS — config.js v2
// Dados estruturais: MAP_POSTOS, POSTOS_DADOS, USUARIOS_ADM
// Concorrentes reais conforme CONCORRENTES_AS do Apps Script v10
// SUPERVISOR_BLOCO atualizado conforme Code.gs (22/06/2026)
// ================================================================

const API_URL = 'https://script.google.com/macros/s/AKfycbwoJ3-g48frwYtMlnpVj5EIYapInPP11OJXrkOPUzCULrbIZWMQW51xFe-Ot4cox00r/exec';

const USUARIOS_ADM = [
  {email:'adm@jbretas.com',  senha:'adm123'},
  {email:'adm2@jbretas.com', senha:'adm456'},
];

// MAP_POSTOS — coordenadas fixas dos postos próprios
const MAP_POSTOS = [
  {k:"JA",                   ap:"P. JA",                    lat:-19.9581, lng:-43.9571, sup:"Mauricio", banda:"Ipiranga"},
  {k:"ITAPOA",               ap:"P. ITAPOA",                lat:-19.9198, lng:-43.9814, sup:"Mauricio", banda:"Shell"},
  {k:"MANGABEIRAS",          ap:"P. MANGABEIRAS",           lat:-19.9600, lng:-43.9610, sup:"Mauricio", banda:"Shell"},
  {k:"DIFERENCIAL",          ap:"P. DIFERENCIAL",           lat:-19.9182, lng:-43.9368, sup:"Mauricio", banda:"Rede Flex"},
  {k:"ARAPONGA",             ap:"P. ARAPONGA",              lat:-19.9620, lng:-43.9500, sup:"Mauricio", banda:"Ipiranga"},
  {k:"URBANO FERRAZ",        ap:"P. URBANO FERRAZ",         lat:-19.9300, lng:-43.9540, sup:"Mauricio", banda:"BR/Petrobras"},
  {k:"ALEX",                 ap:"P. ALEX",                  lat:-19.9550, lng:-43.9320, sup:"Mauricio", banda:"Ipiranga"},
  {k:"BERNARDO",             ap:"P. BERNARDO",              lat:-19.9900, lng:-43.9000, sup:"Mauricio", banda:"Shell"},
  {k:"BOMBOM MATRIZ",        ap:"P. BOMBOM MATRIZ",         lat:-19.9200, lng:-43.9380, sup:"Mauricio", banda:"Ipiranga"},
  {k:"TUNEL",                ap:"P. TUNEL",                 lat:-19.9050, lng:-43.9470, sup:"Fabricio", banda:"BR/Petrobras"},
  {k:"TRANCOSO",             ap:"P. TRANCOSO",              lat:-19.9050, lng:-43.9300, sup:"Fabricio", banda:"Ipiranga"},
  {k:"ANA LUCIA",            ap:"P. ANA LUCIA",             lat:-19.8900, lng:-43.8260, sup:"Fabricio", banda:"BR/Petrobras"},
  {k:"SANTA INES - JOAQUIM", ap:"P. SANTA INES - JOAQUIM",  lat:-19.9350, lng:-44.0630, sup:"Fabricio", banda:"Shell"},
  {k:"SAO BERNARDO",         ap:"P. SAO BERNARDO",          lat:-19.8700, lng:-43.9290, sup:"Fabricio", banda:"Ipiranga"},
  {k:"BAHAMAS",              ap:"P. BAHAMAS",               lat:-19.9150, lng:-43.9300, sup:"Fabricio", banda:"Ipiranga"},
  {k:"SERENA COLIBRI",       ap:"P. SERENA COLIBRI",        lat:-19.8140, lng:-44.0650, sup:"Fabricio", banda:"Ipiranga"},
  {k:"BRUNA",                ap:"P. BRUNA",                 lat:-19.8954, lng:-43.9550, sup:"Fabricio", banda:"BR/Petrobras"},
  {k:"TOPAZIO",              ap:"P. TOPAZIO",               lat:-19.7740, lng:-44.0530, sup:"Paulo",    banda:"BR/Petrobras"},
  {k:"JOCA",                 ap:"P. JOCA",                  lat:-19.9290, lng:-43.9730, sup:"Paulo",    banda:"Ipiranga"},
  {k:"LOURA EMPREENDIMENTOS",ap:"P. LOURA EMPREENDIMENTOS", lat:-19.9384, lng:-44.0901, sup:"Paulo",    banda:"Shell"},
  {k:"AVIVA",                ap:"P. AVIVA",                 lat:-19.7820, lng:-44.0750, sup:"Paulo",    banda:"Ipiranga"},
  {k:"SAO LUIZ RL",          ap:"P. SAO LUIZ RL",           lat:-19.7470, lng:-44.0830, sup:"Paulo",    banda:"Ipiranga"},
  {k:"PLANALTO",             ap:"P. PLANALTO",              lat:-19.8272, lng:-44.0072, sup:"Paulo",    banda:"BR/Petrobras"},
  {k:"SANTA MARIA",          ap:"P. SANTA MARIA",           lat:-19.8000, lng:-44.0750, sup:"Paulo",    banda:"BR/Petrobras"},
  {k:"BOMBOM FILIAL",        ap:"P. BOMBOM FILIAL",         lat:-19.8760, lng:-43.9180, sup:"Paulo",    banda:"Ipiranga"},
  {k:"SANTA INES MINAS",     ap:"P. SANTA INES MINAS",      lat:-19.8880, lng:-43.8230, sup:"Paulo",    banda:"Shell"},
  {k:"OURO BRANCO",          ap:"P. OURO BRANCO",           lat:-20.5200, lng:-43.7300, sup:"Paulo",    banda:"Bandeira Branca"},
  {k:"GLORIA",               ap:"P. GLORIA",                lat:-19.9370, lng:-43.9100, sup:"Gledson",  banda:"Shell"},
  {k:"QUATRO RODAS",         ap:"P. QUATRO RODAS",          lat:-19.8670, lng:-44.0580, sup:"Gledson",  banda:"Ipiranga"},
  {k:"RODRIGO",              ap:"P. RODRIGO",               lat:-19.9480, lng:-44.1980, sup:"Gledson",  banda:"Shell"},
  {k:"LEANDRO",              ap:"P. LEANDRO",               lat:-19.7820, lng:-44.0750, sup:"Gledson",  banda:"Ipiranga"},
  {k:"MIRAGEM JBRETAS",      ap:"P. MIRAGEM JBRETAS",       lat:-19.7820, lng:-43.8850, sup:"Gledson",  banda:"Shell"},
  {k:"BIANCA",               ap:"P. BIANCA",                lat:-20.0400, lng:-44.1500, sup:"Gledson",  banda:"Ipiranga"},
  {k:"BARBOSA - DUDU",       ap:"P. BARBOSA - DUDU",        lat:-19.9330, lng:-44.0030, sup:"Gledson",  banda:"ALE"},
  {k:"BRUNA",                ap:"P. BRUNA",                 lat:-19.8954, lng:-43.9550, sup:"Gledson",  banda:"BR/Petrobras"},
  {k:"ESPACO REAL",          ap:"P. ESPACO REAL",           lat:-21.1300, lng:-44.2570, sup:"Rodrigo",  banda:"BR/Petrobras"},
  {k:"FELIPAO",              ap:"P. FELIPAO",               lat:-19.9230, lng:-43.9900, sup:"Rodrigo",  banda:"BR/Petrobras"},
  {k:"PAIVA E PAIVA COMBUSTIVEL", ap:"PAIVA E PAIVA COMBUSTIVEL", lat:-21.1389, lng:-44.2294, sup:"Rodrigo", banda:"Bandeira Branca"},
];

// POSTOS_DADOS — concorrentes reais conforme Apps Script CONCORRENTES_AS
const POSTOS_DADOS = {
  "ALEX":        {sup:"Mauricio",bandeira:"Ipiranga",combs:["GC","GA","ET","S10"],
    conc:{"REDE FLEX CENTER SUL":{banda:"Rede Flex"},"P. RAJA":{banda:"Bandeira Branca"},"POSTO BARAO":{banda:"Bandeira Branca"},"POSTO WR":{banda:"Bandeira Branca"},"P. NSA. FATIMA (BH)":{banda:"Bandeira Branca"}}},
  "ANA LUCIA":   {sup:"Fabricio",bandeira:"BR/Petrobras",combs:["GC","GA","S10"],
    conc:{"BANDEIRA BRANCA":{banda:"Bandeira Branca"},"MARIANA":{banda:"Bandeira Branca"}}},
  "ARAPONGA":    {sup:"Mauricio",bandeira:"Ipiranga",combs:["GC","GA","ET","S10"],
    conc:{"DUAS PATRIAS":{banda:"Bandeira Branca"},"BOMBOM":{banda:"Bandeira Branca"},"SKY 2":{banda:"Bandeira Branca"},"TIGRES":{banda:"Bandeira Branca"}}},
  "AVIVA":       {sup:"Paulo",bandeira:"Ipiranga",combs:["GC","GA","ET","S10","S500"],
    conc:{"ALE":{banda:"ALE"},"LUMA":{banda:"Bandeira Branca"},"CENTRAL":{banda:"Bandeira Branca"},"POSTO RL":{banda:"Bandeira Branca"},"POSTO DO APOIO":{banda:"Bandeira Branca"}}},
  "BAHAMAS":     {sup:"Fabricio",bandeira:"Ipiranga",combs:["GC","GA","ET"],
    conc:{"POSTO MIGUELAO":{banda:"Bandeira Branca"},"POSTO PAPAI MATRIZ":{banda:"Bandeira Branca"},"POSTO PAPAI FILIAL":{banda:"Bandeira Branca"},"POSTO FLORESTA":{banda:"Bandeira Branca"},"POSTO SAO SEBASTIAO":{banda:"Bandeira Branca"}}},
  "BARBOSA - DUDU":{sup:"Gledson",bandeira:"ALE",combs:["GC","ET","S10"],
    conc:{"POSTO CAICARA":{banda:"Bandeira Branca"},"POSTO CARREFOUR":{banda:"Bandeira Branca"},"POSTO DEL REY":{banda:"Bandeira Branca"}}},
  "BERNARDO":    {sup:"Mauricio",bandeira:"Shell",combs:["GC","ET","S10","S500"],
    conc:{"BALNEARIO AGUA LIMPA":{banda:"Bandeira Branca"},"CHEFAO SHELL":{banda:"Shell"},"CURVO DO RETIRO":{banda:"Bandeira Branca"},"PARADA BOA":{banda:"Bandeira Branca"},"SERENA CANADA":{banda:"Bandeira Branca"},"VIA TORONTO":{banda:"Bandeira Branca"}}},
  "BIANCA":      {sup:"Gledson",bandeira:"Ipiranga",combs:["GC","GA","ET","S10","S500"],
    conc:{"SHELL SUPER LUNA":{banda:"Shell"},"IPIRANGA G. SARZEDO":{banda:"Ipiranga"}}},
  "BOMBOM FILIAL":{sup:"Paulo",bandeira:"Ipiranga",combs:["GC","GA","ET","S10"],
    conc:{"POSTO SUPRA":{banda:"Bandeira Branca"},"POSTO REDEFLEX":{banda:"ALE"},"POSTO NORTE SUL":{banda:"Bandeira Branca"},"REDE MANUELA":{banda:"BR/Petrobras"},"REDE GP SHELL VILARINHO":{banda:"Shell"}}},
  "BOMBOM MATRIZ":{sup:"Mauricio",bandeira:"Ipiranga",combs:["GC","GA","ET"],
    conc:{"REDE AQUI":{banda:"Shell"},"POSTO DUAS PATRIA":{banda:"Bandeira Branca"}}},
  "BRUNA":       {sup:"Gledson",bandeira:"BR/Petrobras",combs:["GC","GA","ET","S10","S500"],
    conc:{"PETRO OURO":{banda:"BR/Petrobras"},"POSTO CARIJO SHELL":{banda:"Shell"},"SAO FRANCISCO":{banda:"Bandeira Branca"},"VILA":{banda:"Bandeira Branca"}}},
  "DIFERENCIAL": {sup:"Mauricio",bandeira:"Rede Flex",combs:["GC","GA","ET","S10"],
    conc:{"POSTO BH":{banda:"Bandeira Branca"},"POSTO VILA":{banda:"Bandeira Branca"},"SAO PEDRO":{banda:"Bandeira Branca"},"REDE FLEX LESTE":{banda:"Rede Flex"}}},
  "ESPACO REAL": {sup:"Rodrigo",bandeira:"BR/Petrobras",combs:["GC","GA","ET","S10","S500"],
    conc:{"BARRA 10":{banda:"Bandeira Branca"},"CANADA":{banda:"Bandeira Branca"},"LILI":{banda:"Bandeira Branca"},"P. ALMEIDA":{banda:"Bandeira Branca"}}},
  "FELIPAO":     {sup:"Rodrigo",bandeira:"BR/Petrobras",combs:["GC","ET","S10","S500"],
    conc:{"ALE MOTOCAR":{banda:"ALE"},"LALAS":{banda:"Bandeira Branca"},"MAXXI":{banda:"Bandeira Branca"},"P. BH":{banda:"Bandeira Branca"},"POSTO REAL":{banda:"Bandeira Branca"},"SANTA CRUZ":{banda:"Bandeira Branca"}}},
  "GLORIA":      {sup:"Gledson",bandeira:"Shell",combs:["GC","ET","S10"],
    conc:{"CAPITAL":{banda:"Bandeira Branca"},"NOSSO POSTO":{banda:"Bandeira Branca"},"POSTO ATUAL":{banda:"Bandeira Branca"}}},
  "ITAPOA":      {sup:"Mauricio",bandeira:"Shell",combs:["GC","GA","ET","S10"],
    conc:{"FLEX VIA EXPRESSA":{banda:"Bandeira Branca"},"PHOENIX AMAZONAS":{banda:"Bandeira Branca"},"PIO XII AMAZONAS":{banda:"Bandeira Branca"},"POSTO FRANCISCO DE SA":{banda:"Bandeira Branca"},"POSTO OLIMAR":{banda:"Bandeira Branca"},"POSTO QUICK":{banda:"Bandeira Branca"},"POSTO WAP":{banda:"Bandeira Branca"},"REDE FLEX AMAZONAS":{banda:"Rede Flex"},"POSTO ITAPOA":{banda:"Bandeira Branca"}}},
  "JA":          {sup:"Mauricio",bandeira:"Ipiranga",combs:["GC","GA","ET","S10","OCT"],
    conc:{"P. RAJA":{banda:"Bandeira Branca"},"POSTO WR":{banda:"Bandeira Branca"},"REDE FLEX CENTER SUL":{banda:"Rede Flex"}}},
  "JOCA":        {sup:"Paulo",bandeira:"Ipiranga",combs:["GC","ET","S10"],
    conc:{"AQUI":{banda:"Rede Aqui"},"ATLANTICO":{banda:"Bandeira Branca"},"CHAVES":{banda:"Bandeira Branca"}}},
  "LEANDRO":     {sup:"Gledson",bandeira:"Ipiranga",combs:["GC","GA","ET","S10","S500"],
    conc:{"CAPITAL":{banda:"Bandeira Branca"},"SERRANO":{banda:"Bandeira Branca"},"LUBRIMIL":{banda:"Bandeira Branca"},"SHELL (BH)":{banda:"Shell"}}},
  "LOURA EMPREENDIMENTOS":{sup:"Paulo",bandeira:"Shell",combs:["GC","GA","ET","S10","S500"],
    conc:{"FAISCA":{banda:"Bandeira Branca"},"SAO GERALDO":{banda:"Bandeira Branca"},"MIL":{banda:"Bandeira Branca"},"SHELL SANTO POSTO":{banda:"Shell"},"PADUA":{banda:"Bandeira Branca"},"SIGA PETRO":{banda:"Siga Petro"}}},
  "MANGABEIRAS": {sup:"Mauricio",bandeira:"Shell",combs:["GC","GA","ET","S10"],
    conc:{"VILA":{banda:"Bandeira Branca"},"OURO":{banda:"Bandeira Branca"},"REDE FLEX SIGMA":{banda:"Rede Flex"},"ALTO SION":{banda:"Bandeira Branca"},"PIAZZA":{banda:"Bandeira Branca"},"CORUJAO":{banda:"Bandeira Branca"}}},
  "MIRAGEM JBRETAS":{sup:"Gledson",bandeira:"Shell",combs:["GC","ET","S10","S500"],
    conc:{"XAVANTE":{banda:"Bandeira Branca"},"CATALAO":{banda:"Bandeira Branca"}}},
  "OURO BRANCO": {sup:"Paulo",bandeira:"Bandeira Branca",combs:["GC","GA","ET","S10"],
    conc:{"POSTO PRAIA 01":{banda:"Ipiranga"},"POSTO CHAMPION":{banda:"Bandeira Branca"},"POSTO PRAIA 02":{banda:"Ipiranga"},"POSTO REDE SANTANA":{banda:"Bandeira Branca"}}},
  "PAIVA E PAIVA COMBUSTIVEL": {sup:"Rodrigo",bandeira:"Bandeira Branca",combs:["GC","GA","ET","S10","S500"],
    conc:{"POSTO DUDU":{banda:"Bandeira Branca"},"POSTO IPIRANGA":{banda:"Ipiranga"},"POSTO PATIO":{banda:"Bandeira Branca"},"POSTO BH":{banda:"Bandeira Branca"},"POSTO SAO JOAO":{banda:"Bandeira Branca"}}},
  "PLANALTO":    {sup:"Paulo",bandeira:"BR/Petrobras",combs:["GC","GA","ET","S10","S500"],
    conc:{"ALE SENT. BAIRRO":{banda:"ALE"},"BR OLIMPIO MOURAO (FALCAO)":{banda:"BR/Petrobras"},"CAMOES (AV.PORTUGAL)":{banda:"Bandeira Branca"},"P. ENTRADA OBRIGATORIA":{banda:"Bandeira Branca"},"SAO BERNARDO":{banda:"Bandeira Branca"}}},
  "QUATRO RODAS":{sup:"Gledson",bandeira:"Ipiranga",combs:["GC","GA","ET","S10"],
    conc:{"REDE FLEX PORTAL":{banda:"Rede Flex"},"POSTO VILA":{banda:"Bandeira Branca"},"REDE FLEX TROVAO":{banda:"Rede Flex"},"POSTO NOVO":{banda:"Bandeira Branca"},"REDE AQUI":{banda:"Rede Aqui"}}},
  "RODRIGO":     {sup:"Gledson",bandeira:"Shell",combs:["GC","GA","ET","S10","S500"],
    conc:{"ATLANTA":{banda:"Bandeira Branca"},"ALE MILLENIUM":{banda:"ALE"},"VILA LIBERDADE":{banda:"Bandeira Branca"},"VILA PIRATA":{banda:"Bandeira Branca"},"REDE AQUI":{banda:"Rede Aqui"}}},
  "SANTA INES - JOAQUIM":{sup:"Fabricio",bandeira:"Shell",combs:["GC","GA","ET","S10","S500"],
    conc:{"POSTO BR NOVO":{banda:"BR/Petrobras"},"POSTO CEASA":{banda:"Bandeira Branca"},"POSTO REMO":{banda:"Bandeira Branca"},"SANTANA NOVO":{banda:"Bandeira Branca"},"VILA BETO":{banda:"Bandeira Branca"}}},
  "SANTA INES MINAS":{sup:"Paulo",bandeira:"Shell",combs:["GC","GA","ET","S10"],
    conc:{"TREVINHO":{banda:"Bandeira Branca"},"REDE AQUI":{banda:"Rede Aqui"}}},
  "SANTA MARIA": {sup:"Gledson",bandeira:"BR/Petrobras",combs:["GC","ET","S10"],
    conc:{"MANACAS":{banda:"Bandeira Branca"},"POSTO DUO DRIVE":{banda:"Bandeira Branca"}}},
  "SAO BERNARDO":{sup:"Fabricio",bandeira:"Ipiranga",combs:["GC","GA","ET"],
    conc:{"POSTO FLORAMAR":{banda:"Bandeira Branca"},"POSTO MARIO VERNECK":{banda:"Ipiranga"},"POSTO MINEIRO":{banda:"ALE"},"POSTO ESTACAO":{banda:"Bandeira Branca"},"REDE FENIX SENTIDO BH CENTRO":{banda:"Shell"},"REDE FLEX CRISTIANO MACHADO":{banda:"Rede Flex"},"POSTO WAP CRIANO MACHADO":{banda:"Shell"}}},
  "SAO LUIZ RL": {sup:"Paulo",bandeira:"Ipiranga",combs:["GC","ET","S10","S500"],conc:{}},
  "SERENA COLIBRI":{sup:"Fabricio",bandeira:"Ipiranga",combs:["GC","GA","ET","S10","S500"],
    conc:{"REDE FLEX POETA":{banda:"Rede Flex"},"REDE FLEX CELT":{banda:"Rede Flex"},"PHOENIX SAO LUIZ":{banda:"Bandeira Branca"},"VILA COMETA":{banda:"Bandeira Branca"},"REDE FLEX TATIANA":{banda:"Rede Flex"},"TROPICO":{banda:"Bandeira Branca"},"POSTO DEL REI":{banda:"Bandeira Branca"}}},
  "TOPAZIO":     {sup:"Paulo",bandeira:"BR/Petrobras",combs:["GC","GA","ET","S10"],
    conc:{"BOMBOM":{banda:"Bandeira Branca"},"ENSEADA AZUL":{banda:"Bandeira Branca"},"G&P":{banda:"Bandeira Branca"},"MANUELA":{banda:"Bandeira Branca"},"PICA PAU":{banda:"Bandeira Branca"},"REDE FLEX CENTER NORTE":{banda:"Rede Flex"},"VAQUINHA":{banda:"Bandeira Branca"}}},
  "TRANCOSO":    {sup:"Fabricio",bandeira:"Ipiranga",combs:["GC","GA","ET","S10"],
    conc:{"BARUC":{banda:"Bandeira Branca"},"IPIRANGA":{banda:"Ipiranga"},"POSTO BR PARQUE":{banda:"BR/Petrobras"}}},
  "TUNEL":       {sup:"Fabricio",bandeira:"BR/Petrobras",combs:["GC","GA","ET"],
    conc:{"PETRO OURO":{banda:"BR/Petrobras"},"PASSARELA":{banda:"Bandeira Branca"},"REDE ALIANCA":{banda:"Rede Aliança"},"SANTANA":{banda:"Bandeira Branca"}}},
  "URBANO FERRAZ":{sup:"Mauricio",bandeira:"BR/Petrobras",combs:["GC","GA","ET","S10","PODIUM"],
    conc:{"SHELL LIBERDADE":{banda:"Shell"},"TUPI":{banda:"Bandeira Branca"},"BEIJA FLOR":{banda:"Bandeira Branca"},"SHELL WERVIN":{banda:"Shell"}}},
};

// Cores
const SUPCOR = {Mauricio:'#00e5a0',Paulo:'#4895ef',Fabricio:'#f9c74f',Gledson:'#c77dff',Rodrigo:'#ff6b6b'};
const BCOR   = {"Rede Flex":"#00e5a0","Ipiranga":"#f9c74f","Shell":"#e8c84a","BR/Petrobras":"#4db6ac","ALE":"#ff6b6b","Bandeira Branca":"#8892a4","Rede Aqui":"#ff9800","Siga Petro":"#ba68c8","Rede Aliança":"#ff7043"};

// ================================================================
// SUPERVISOR_BLOCO — atualizado conforme Code.gs (22/06/2026)
// Removidos: CEASA (= SANTA INES), BEATRIZ (= PAIVA E PAIVA)
// Adicionados: DUDU, BRUNA→Gledson, OURO BRANCO→Paulo,
//              SANTA MARIA→Gledson, BEATRIZ→Rodrigo
// ================================================================
const SUPERVISOR_BLOCO = {
  "J A":"Mauricio",          "MANGABEIRAS":"Mauricio",   "URBANO":"Mauricio",
  "DIFERENCIAL":"Mauricio",  "ARAPONGA":"Mauricio",      "ITAPOA":"Mauricio",
  "ALEX":"Mauricio",         "BERNARDO":"Mauricio",      "BOMBOM MATRIZ":"Mauricio",
  "TUNEL":"Fabricio",        "TRANCOSO":"Fabricio",      "ANA LUCIA":"Fabricio",
  "SANTA INES":"Fabricio",   "SAO BERNARDO":"Fabricio",  "BAHAMAS":"Fabricio",
  "COLIBRI":"Fabricio",      "PLANALTO":"Fabricio",
  "TOPAZIO":"Paulo",         "JOCA":"Paulo",             "LOURA":"Paulo",
  "AVIVA":"Paulo",           "SAO LUIZ":"Paulo",
  "SANTA INES MINAS":"Paulo","OURO BRANCO":"Paulo",
  "BOMBOM FILIAL":"Paulo",
  "GLORIA":"Gledson",        "4RODAS":"Gledson",         "RODRIGO":"Gledson",
  "LEANDRO":"Gledson",       "MIRAGEM":"Gledson",        "BIANCA":"Gledson",
  "DUDU":"Gledson",          "BRUNA":"Gledson",          "SANTA MARIA":"Gledson",
  "ESPACO REAL":"Rodrigo",   "FELIPAO":"Rodrigo",        "BEATRIZ":"Rodrigo",
  "PAIVA PAIVA":"Rodrigo",
};
